### ISSUE TITLE
Handle multiple flushes of the same file

### ISSUE THREAD

**Issue by maswan** [neicnordic/endit#1]
Right now if dCache flushes a file multiple times it'll get multiple copies in the TSM archive which leads to waste of space and slower retrieves.

**Comment by ZNikke** [comment]
The frequency of this occurring should be much lower now with some of the functionality moved to the ENDIT dCache plugin.

While it still can occur, we believe that this is more or less a theoretical possibility.

If you experience this issue in production using current releases of the ENDIT dCache plugin and the ENDIT daemons, please open a new issue.
