### ISSUE TITLE
Centralised logging

### ISSUE THREAD

**Issue by maswan** [neicnordic/endit#10]
Tape usage statistics will need some centralized logging of data to generate https://twiki.cern.ch/twiki/bin/view/HEPTape/TapeMetricsJSON

Things to include: hsminstance, total number of files, number of tapes

Each tape mount with: time, number of files, number of bytes

Errors (i.e. all local logging should also be sent remote), for OoD enjoyment

Idea: See if we can use dcache's log4j central logging stuff, so we only have to implement a sender, not a collector.

**Comment by ZNikke** [comment]
Implementing a logging framework in the ENDIT daemons makes this component more complex than we want it to be.

For NDGF centralized logging will be implemented by collecting all logs to a central location by other means and processing them there.

Whatever method is used for this, it can be implemented outside of ENDIT.
